version: 2.1

commands:
  install-volta:
    description: Install volta to manage Node/pnpm versions
    steps:
      - run:
          name: Install volta
          # Teach the volta installer to update Circle's special env
          # file instead of the default.
          command: |
            curl https://get.volta.sh | PROFILE="$BASH_ENV" bash

  setup-node:
    parameters:
      node-version:
        type: string
        default: ''
    steps:
      - install-volta
      - checkout
      - run: volta install node@<< parameters.node-version >>
      - run: volta install pnpm@8
      - run: node --version
      - run: pnpm --version
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      # - run:
      #     name: Install pnpm package manager
      #     command: |
      #       corepack enable
      #       corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
            - package/node_modules
            - example/node_modules

jobs:
  NodeJS:
    parameters:
      node-version:
        type: string
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node:
          node-version: <<parameters.node-version>>
      - run: pnpm run test:ci
      - store_test_results:
          path: junit.xml

  Prettier:
    docker:
    - image: cimg/base:stable
    steps:
      - setup-node
      - run: pnpm run prettier-check

workflows:
  Build:
    jobs:
      - NodeJS:
          name: NodeJS << matrix.node-version >>
          matrix:
            parameters:
              node-version:
                - "16"
                - "18"
      - Prettier